
CREATE TABLE PESSOA (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(80),
  SALARIO FLOAT NOT NULL,
  DEPTID INT NOT NULL
);

CREATE TABLE DEPARTAMENTO (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  NOME VARCHAR(30)
);

INSERT INTO PESSOA(NOME,SALARIO,DEPTID) VALUES ('Joe', 70000, 1);
INSERT INTO PESSOA(NOME,SALARIO,DEPTID) VALUES ('Henry', 80000, 2);
INSERT INTO PESSOA(NOME,SALARIO,DEPTID) VALUES ('Sam', 60000, 2);
INSERT INTO PESSOA(NOME,SALARIO,DEPTID) VALUES ('Max', 90000, 1);
INSERT INTO PESSOA(NOME,SALARIO,DEPTID) VALUES ('Max', 90000, 1);

INSERT INTO DEPARTAMENTO(NOME) VALUES ('TI');
INSERT INTO DEPARTAMENTO(NOME) VALUES ('Vendas');

SELECT * FROM PESSOA;
SELECT * FROM DEPARTAMENTO;


SELECT 
    D.NOME AS DEPARTAMENTO,
    P.NOME AS PESSOA,
    P.SALARIO
FROM PESSOA P
INNER JOIN DEPARTAMENTO D ON P.DEPTID = D.ID ORDER BY P.SALARIO DESC;